/**
 * Rule 5 is a legal constraint, not a style preference. Section 230 covers
 * hosting user content; a false accusation generated by Guardian is Guardian's
 * own speech. Guardian emits risk tiers and evidence bundles for human review
 * and never asserts that a person is a predator.
 *
 * This module is the enforcement point. Every user-facing string, log message,
 * webhook rationale and mod-channel alert passes through `assertNoAccusation`,
 * and a test walks the source tree for literals that would fail it.
 */

export interface ForbiddenPattern {
  pattern: RegExp;
  why: string;
  /** A phrasing that says the same thing without the accusation. */
  instead: string;
}

export const FORBIDDEN_PATTERNS: ForbiddenPattern[] = [
  {
    pattern: /\b(is|are|was|were|being)\s+(a\s+)?(predator|pedophile|paedophile|groomer|abuser|offender|criminal)s?\b/i,
    why: "states a conclusion about a person",
    instead: "describe the behaviour in the traffic and the tier",
  },
  {
    pattern: /\b(this|the)\s+(user|account|member|actor|person)\s+is\s+(a\s+)?\w*(predator|pedophile|groomer|abuser)/i,
    why: "labels an account as a person of a criminal type",
    instead: "say which signals fired on which conversation",
  },
  {
    pattern: /\b(confirmed|known|proven|identified)\s+(predator|pedophile|paedophile|groomer|child abuser|sex offender)\b/i,
    why: "asserts a finding Guardian cannot make",
    instead: "reviewer-confirmed tier T3, pending report",
  },
  {
    pattern: /\b(guilty|committed a crime|broke the law|is illegal)\b/i,
    why: "states a legal conclusion",
    instead: "describe the signal and let the reviewer and the authorities decide",
  },
  {
    pattern: /\bcaught\s+(a\s+)?(predator|pedo|groomer)/i,
    why: "vigilante framing, and the product refuses that posture",
    instead: "tier assigned, evidence bundle available for review",
  },
  {
    pattern: /\b(grooming|predatory|criminal)\s+(detected|confirmed|found)\b/i,
    why: "asserts the offence rather than the signal",
    instead: "signals consistent with the documented pattern were recorded",
  },
];

export interface AccusationFinding {
  match: string;
  why: string;
  instead: string;
}

export function findAccusations(text: string): AccusationFinding[] {
  const out: AccusationFinding[] = [];
  for (const rule of FORBIDDEN_PATTERNS) {
    const hit = rule.pattern.exec(text);
    if (hit) out.push({ match: hit[0], why: rule.why, instead: rule.instead });
  }
  return out;
}

export function isAccusatory(text: string): boolean {
  return findAccusations(text).length > 0;
}

/**
 * Throws rather than sanitizing. A silent rewrite would hide the fact that some
 * code path is trying to make an assertion the product must not make.
 */
export function assertNoAccusation(text: string, where: string): string {
  const findings = findAccusations(text);
  if (findings.length === 0) return text;
  const first = findings[0]!;
  throw new Error(
    `${where}: string "${first.match}" ${first.why}. Guardian never labels a person (CLAUDE.md rule 5). Instead: ${first.instead}.`,
  );
}
