import { assertNoAccusation, type EvidenceBundle, type Tier, type WebhookPayload } from "@guardian/schema";

/**
 * Mod-channel alerts. Every string here goes through the accusation guard
 * before it is sent, because a false accusation generated by Guardian is
 * Guardian's own speech and is not covered by Section 230
 * (CLAUDE.md rule 5, DESIGN.md 2).
 *
 * The alert names accounts by their Discord id, describes what the traffic did,
 * and tells the moderator what the tier means and what to do next. It does not
 * tell them what kind of person they are looking at.
 */

export interface AlertInput {
  tier: Tier;
  /** Discord user ids. The mod channel is the customer's own space. */
  actorId: string;
  targetId: string;
  channelId: string;
  rationale: string[];
  criticalSignals: string[];
  stagesHit: string[];
  bundleId?: string;
}

const TIER_HEADLINE: Record<Tier, string> = {
  T0: "No action needed",
  T1: "Watch",
  T2: "Needs a human look",
  T3: "Reviewer confirmed",
};

const TIER_GUIDANCE: Record<Tier, string> = {
  T0: "Nothing to do.",
  T1: "Recorded for 30 days. No action requested. If you see more, it will escalate on its own.",
  T2: "Read the excerpts below and decide. If you believe a child is being harmed, file at report.cybertip.org using the bundle. Do not message either account about this.",
  T3: "A human reviewer confirmed this. The evidence bundle is preserved for one year.",
};

export function buildModAlert(input: AlertInput): string {
  const lines: string[] = [];

  lines.push(`**${TIER_HEADLINE[input.tier]}** (tier ${input.tier})`);
  lines.push(`Conversation: <@${input.actorId}> to <@${input.targetId}> in <#${input.channelId}>`);

  if (input.stagesHit.length > 0) {
    lines.push(`Pattern stages recorded: ${input.stagesHit.join(", ")}.`);
  }
  for (const reason of input.rationale.slice(0, 6)) {
    lines.push(`- ${reason}`);
  }
  if (input.criticalSignals.length > 0) {
    lines.push(`Forcing signal: ${input.criticalSignals.join(", ")}.`);
  }

  lines.push("");
  lines.push(TIER_GUIDANCE[input.tier]);
  lines.push(
    "This is a risk tier produced from message patterns. It is not a finding about any person, and Guardian has made no report to anyone.",
  );
  if (input.bundleId) lines.push(`Evidence bundle: \`${input.bundleId}\``);

  return assertNoAccusation(lines.join("\n"), "buildModAlert");
}

/** Short line for the ephemeral reply after a slash command. */
export function buildStatusLine(payload: WebhookPayload): string {
  return assertNoAccusation(
    `Tier ${payload.tier} recorded on one conversation pair at ${payload.scoredAt.toISOString()}. Lexicon ${payload.versions.lexiconVersion}, fusion ${payload.versions.fusionVersion}.`,
    "buildStatusLine",
  );
}

/**
 * What the owner takes to report.cybertip.org. Guardian drafts it; the server
 * owner is the reporter of record for the Discord surface (DESIGN.md 8), and
 * the bot never submits anything on their behalf.
 */
export function buildReportDraft(bundle: EvidenceBundle, rationale: string[]): string {
  const lines: string[] = [
    "CyberTipline report draft",
    "",
    "Guardian prepared this draft from message patterns in your server. You are the reporter. Review every line, correct anything that is wrong, and submit it yourself at report.cybertip.org. Guardian does not submit reports for Discord servers and does not contact law enforcement.",
    "",
    `Bundle id: ${bundle.bundleId}`,
    `Server: ${bundle.provenance.map((p) => p.sourceId).join(", ")}`,
    `Tier at export: ${bundle.tier}`,
    `Generated: ${bundle.generatedAt.toISOString()}`,
    `Versions: model ${bundle.versions.modelVersion}, lexicon ${bundle.versions.lexiconVersion}, fusion ${bundle.versions.fusionVersion}`,
    `Audit chain head at export: ${bundle.auditHead}`,
    "",
    "Why this was surfaced",
    ...rationale.map((r) => `- ${r}`),
    "",
    "Message timeline",
  ];

  for (const row of bundle.timeline) {
    const who = row.direction === "actor_to_target" ? "older account" : "younger account";
    const media = row.mediaSha256
      ? ` [media sha256 ${row.mediaSha256}, scanner verdict ${row.knownCsamVerdict ?? "not run"}]`
      : "";
    lines.push(`${row.ts.toISOString()} ${who} in ${row.channel}: ${row.excerpt ?? "(no text retained)"}${media}`);
  }

  lines.push(
    "",
    "Guardian holds no images or video. Media appears above as a hash and, where your platform ran one, the scanner's verdict.",
    "Preserve the original messages in your server. Do not delete them, and do not confront either account.",
  );

  return assertNoAccusation(lines.join("\n"), "buildReportDraft");
}
