import type { AuditLog } from "@guardian/audit";
import { AGE_BANDS, assertNoAccusation, type AgeBand, type Tier } from "@guardian/schema";
import type { RESTPostAPIChatInputApplicationCommandsJSONBody } from "discord.js";
import { buildReportDraft } from "./alerts.js";
import { defaultGuildConfig, isReady, type GuildConfig, type GuildConfigStore } from "./config.js";
import type { BotPipeline } from "./pipeline.js";

/**
 * Slash commands under /guardian.
 *
 * The command tree is plain data in the shape Discord's REST API takes, so this
 * module has no runtime dependency on discord.js and `handleCommand` runs in a
 * test with nothing but fakes. bot.ts turns an interaction into a
 * `CommandInput` and a `CommandReply` back into an ephemeral response.
 *
 * Three rules from DESIGN.md 8 and CLAUDE.md shape every branch here. Replies
 * are ephemeral, always: nothing the bot says about a conversation goes into a
 * public channel. The owner is the reporter of record, so `export` hands them a
 * draft and never files anything. And every reply passes through the
 * accusation guard, because a false accusation generated by Guardian is
 * Guardian's own speech (rule 5).
 */

export const COMMAND_NAME = "guardian";

export const SUBCOMMANDS = [
  "setup",
  "role",
  "trusted",
  "timeout",
  "exclude",
  "status",
  "export",
  "verify",
] as const;
export type Subcommand = (typeof SUBCOMMANDS)[number];

/**
 * Anyone in the server may run status, but what it answers depends on the
 * caller. A member gets the overt disclosure rule 3 requires: Guardian is here
 * and whether it is scoring. Only Manage Server sees the settings, and in
 * particular the list of channels Guardian does not read, because that list is
 * a map of where it is blind.
 */
export const OPEN_SUBCOMMANDS: readonly Subcommand[] = ["status"];

/** Bounds for the opt-in T2 timeout, matching guildConfigSchema. */
export const TIMEOUT_MIN_MINUTES = 1;
export const TIMEOUT_MAX_MINUTES = 10_080;

/** Discord ApplicationCommandOptionType values, written out so no enum import is needed at runtime. */
const OptionType = {
  Subcommand: 1,
  String: 3,
  Integer: 4,
  Boolean: 5,
  User: 6,
  Channel: 7,
  Role: 8,
} as const;

/** ChannelType.GuildText. Alerts and exclusions only make sense on text channels. */
const GUILD_TEXT = 0;

/** InteractionContextType.Guild. The bot has no business in a DM. */
const GUILD_CONTEXT = 0;

const BAND_LABELS: Record<AgeBand, string> = {
  UNDER_9: "under 9",
  A9_12: "9 to 12",
  A13_15: "13 to 15",
  A16_17: "16 to 17",
  A18_20: "18 to 20",
  A21_PLUS: "21 and over",
  UNKNOWN: "unknown (no band)",
};

export const GUARDIAN_COMMAND: RESTPostAPIChatInputApplicationCommandsJSONBody = {
  name: COMMAND_NAME,
  description: "Guardian: risk tiers and evidence bundles for your moderators",
  contexts: [GUILD_CONTEXT],
  options: [
    {
      type: OptionType.Subcommand,
      name: "setup",
      description: "Pick the channel alerts go to and turn scoring on",
      options: [
        {
          type: OptionType.Channel,
          name: "channel",
          description: "Private moderator channel for tier alerts",
          required: true,
          channel_types: [GUILD_TEXT],
        },
        {
          type: OptionType.Boolean,
          name: "enable",
          description: "Start scoring now (default: yes)",
          required: false,
        },
      ],
    },
    {
      type: OptionType.Subcommand,
      name: "role",
      description: "Tell Guardian which age band a role means",
      options: [
        { type: OptionType.Role, name: "role", description: "Server role", required: true },
        {
          type: OptionType.String,
          name: "band",
          description: "Age band for members holding this role",
          required: true,
          choices: AGE_BANDS.map((band) => ({ name: BAND_LABELS[band], value: band })),
        },
      ],
    },
    {
      type: OptionType.Subcommand,
      name: "trusted",
      description: "Add or remove a trusted role (moderators, teachers, parents)",
      options: [{ type: OptionType.Role, name: "role", description: "Server role", required: true }],
    },
    {
      type: OptionType.Subcommand,
      name: "timeout",
      description: "Opt in or out of a temporary timeout when a pair reaches tier T2",
      options: [
        {
          type: OptionType.String,
          name: "mode",
          description: "on or off",
          required: true,
          choices: [
            { name: "on", value: "on" },
            { name: "off", value: "off" },
          ],
        },
        {
          type: OptionType.Integer,
          name: "minutes",
          description: `Timeout length, ${TIMEOUT_MIN_MINUTES} to ${TIMEOUT_MAX_MINUTES} minutes`,
          required: false,
          min_value: TIMEOUT_MIN_MINUTES,
          max_value: TIMEOUT_MAX_MINUTES,
        },
      ],
    },
    {
      type: OptionType.Subcommand,
      name: "exclude",
      description: "Toggle a channel Guardian should not read",
      options: [
        {
          type: OptionType.Channel,
          name: "channel",
          description: "Channel to exclude or include again",
          required: true,
          channel_types: [GUILD_TEXT],
        },
      ],
    },
    {
      type: OptionType.Subcommand,
      name: "status",
      description: "Show Guardian's settings and recent activity in this server",
    },
    {
      type: OptionType.Subcommand,
      name: "export",
      description: "Draft a CyberTipline report bundle for one conversation pair",
      options: [
        {
          type: OptionType.User,
          name: "sender",
          description: "The account whose messages were scored",
          required: true,
        },
        {
          type: OptionType.User,
          name: "recipient",
          description: "The account those messages were sent to",
          required: true,
        },
      ],
    },
    {
      type: OptionType.Subcommand,
      name: "verify",
      description: "Check the audit chain for tampering",
    },
  ],
};

export type CommandRequest =
  | { name: "setup"; channelId: string; enable?: boolean | null }
  | { name: "role"; roleId: string; band: string }
  | { name: "trusted"; roleId: string }
  | { name: "timeout"; mode: "on" | "off"; minutes?: number | null }
  | { name: "exclude"; channelId: string }
  | { name: "status" }
  | { name: "export"; senderId: string; recipientId: string }
  | { name: "verify" };

export interface CommandInput {
  guildId: string | null;
  invokerId: string;
  /** Whether the invoker holds Manage Server. Resolved by the gateway edge. */
  canManageGuild: boolean;
  request: CommandRequest;
}

export interface ReplyFile {
  name: string;
  /** UTF-8 text. The bot never attaches anything else. */
  content: string;
}

export interface CommandReply {
  content: string;
  /** Always true. No reply to a command is ever public. */
  ephemeral: true;
  files?: ReplyFile[];
}

/** What the bot remembers about a scored pair, keyed by hashed uids. */
export interface PairHistory {
  tier: Tier;
  rationale: string[];
  /** Messages scored on this pair since the bot started watching. */
  messages: number;
  lastSeenAt: Date;
}

/**
 * Pair memory is per guild. The bot serves many servers from one process under
 * one customer id and one salt, so two Discord ids hash the same everywhere;
 * without the guild in the key an owner could export a conversation that
 * happened in someone else's server (CLAUDE.md rule 8).
 */
export interface PairLookup {
  history(guildId: string, actorUid: string, targetUid: string): Promise<PairHistory | null>;
  /** Pairs at T1 and T2 in this guild touched since `since`. */
  recentTierCounts(guildId: string, since: Date): Promise<{ T1: number; T2: number }>;
}

export interface CommandDeps {
  configs: GuildConfigStore;
  pipeline: Pick<BotPipeline, "exportBundle">;
  audit: Pick<AuditLog, "verify" | "head">;
  pairs: PairLookup;
  /** Per-customer salted hash, the same one the pipeline applies. */
  hashUid: (discordId: string) => string;
  now?: () => Date;
}

/**
 * In-process pair memory. bot.ts feeds it from each pipeline result; the
 * Prisma-backed kernel store replaces the counting half when it lands.
 */
export class MemoryPairLookup implements PairLookup {
  private readonly pairs = new Map<string, PairHistory>();

  record(
    guildId: string,
    actorUid: string,
    targetUid: string,
    tier: Tier,
    rationale: string[],
    at: Date,
  ): void {
    const key = pairKey(guildId, actorUid, targetUid);
    const previous = this.pairs.get(key);
    this.pairs.set(key, {
      // A pair's tier is its trajectory; a quiet message after a T2 does not lower it.
      tier: previous && tierRank(previous.tier) > tierRank(tier) ? previous.tier : tier,
      rationale: rationale.length > 0 ? rationale : (previous?.rationale ?? []),
      messages: (previous?.messages ?? 0) + 1,
      lastSeenAt: at,
    });
  }

  async history(guildId: string, actorUid: string, targetUid: string): Promise<PairHistory | null> {
    return this.pairs.get(pairKey(guildId, actorUid, targetUid)) ?? null;
  }

  async recentTierCounts(guildId: string, since: Date): Promise<{ T1: number; T2: number }> {
    const counts = { T1: 0, T2: 0 };
    const prefix = `${guildId}:`;
    for (const [key, pair] of this.pairs) {
      if (!key.startsWith(prefix)) continue;
      if (pair.lastSeenAt < since) continue;
      if (pair.tier === "T1") counts.T1 += 1;
      if (pair.tier === "T2") counts.T2 += 1;
    }
    return counts;
  }
}

/** Guild first, so one server's pair state can never be read from another. */
function pairKey(guildId: string, actorUid: string, targetUid: string): string {
  return `${guildId}:${actorUid}:${targetUid}`;
}

function tierRank(tier: Tier): number {
  return Number(tier.slice(1));
}

/** A pair can be bundled when it was scored and something above T0 retained text. */
export function isBundleable(history: PairHistory | null): boolean {
  return history !== null && history.messages > 0 && history.tier !== "T0";
}

export function isAgeBand(value: string): value is AgeBand {
  return (AGE_BANDS as readonly string[]).includes(value);
}

export function isValidTimeoutMinutes(minutes: number): boolean {
  return Number.isInteger(minutes) && minutes >= TIMEOUT_MIN_MINUTES && minutes <= TIMEOUT_MAX_MINUTES;
}

const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

export async function handleCommand(input: CommandInput, deps: CommandDeps): Promise<CommandReply> {
  const { request } = input;
  const where = `handleCommand.${request.name}`;

  if (!input.guildId) {
    return reply("Guardian commands run inside a server. There is nothing to configure from a direct message.", where);
  }
  if (!OPEN_SUBCOMMANDS.includes(request.name) && !input.canManageGuild) {
    return reply(
      "Only members with the Manage Server permission can change Guardian's settings or export a bundle. Anyone can run /guardian status.",
      where,
    );
  }

  const config = (await deps.configs.get(input.guildId)) ?? defaultGuildConfig(input.guildId);

  switch (request.name) {
    case "setup": {
      config.modChannelId = request.channelId;
      config.enabled = request.enable ?? true;
      await deps.configs.put(config);
      return reply(
        config.enabled
          ? `Alerts will go to <#${request.channelId}>. Scoring is on. Map your age roles with /guardian role so age gaps count.`
          : `Alerts will go to <#${request.channelId}>. Scoring is off until you run /guardian setup with enable set to true.`,
        where,
      );
    }

    case "role": {
      if (!isAgeBand(request.band)) {
        return reply(
          `"${request.band}" is not an age band. Use one of: ${AGE_BANDS.join(", ")}. Nothing was changed.`,
          where,
        );
      }
      config.roleBands = { ...config.roleBands, [request.roleId]: request.band };
      await deps.configs.put(config);
      return reply(
        `Members with <@&${request.roleId}> are now treated as ${BAND_LABELS[request.band]}. Guardian stores the band, never a birthdate.`,
        where,
      );
    }

    case "trusted": {
      const present = config.trustedRoleIds.includes(request.roleId);
      config.trustedRoleIds = present
        ? config.trustedRoleIds.filter((id) => id !== request.roleId)
        : [...config.trustedRoleIds, request.roleId];
      await deps.configs.put(config);
      return reply(
        present
          ? `<@&${request.roleId}> is no longer a trusted role.`
          : `<@&${request.roleId}> is now a trusted role. Weighting is reduced for these accounts; they are still scored.`,
        where,
      );
    }

    case "timeout": {
      if (request.mode === "off") {
        config.autoTimeoutOnT2 = false;
        await deps.configs.put(config);
        return reply("Automatic timeout on tier T2 is off. Alerts still go to the mod channel.", where);
      }
      if (request.minutes !== undefined && request.minutes !== null) {
        if (!isValidTimeoutMinutes(request.minutes)) {
          return reply(
            `Timeout length must be a whole number of minutes from ${TIMEOUT_MIN_MINUTES} to ${TIMEOUT_MAX_MINUTES}. Nothing was changed.`,
            where,
          );
        }
        config.autoTimeoutMinutes = request.minutes;
      }
      config.autoTimeoutOnT2 = true;
      await deps.configs.put(config);
      return reply(
        `Automatic timeout on tier T2 is on, ${config.autoTimeoutMinutes} minutes. This is friction while a moderator reads the alert, not a verdict, and any moderator can lift it.`,
        where,
      );
    }

    case "exclude": {
      const present = config.excludedChannelIds.includes(request.channelId);
      config.excludedChannelIds = present
        ? config.excludedChannelIds.filter((id) => id !== request.channelId)
        : [...config.excludedChannelIds, request.channelId];
      await deps.configs.put(config);
      return reply(
        present
          ? `<#${request.channelId}> is included again.`
          : `<#${request.channelId}> is excluded. Guardian will not read messages there.`,
        where,
      );
    }

    case "status": {
      // A member is told Guardian is here and whether it is scoring, and
      // nothing else. Which channels are excluded, which roles are trusted and
      // how many pairs are at each tier stay with Manage Server.
      if (!input.canManageGuild) return reply(formatPublicStatus(config), where);
      const now = deps.now?.() ?? new Date();
      const counts = await deps.pairs.recentTierCounts(input.guildId, new Date(now.getTime() - WEEK_MS));
      const head = await deps.audit.head();
      return reply(formatStatus(config, counts, head), where);
    }

    case "export": {
      if (request.senderId === request.recipientId) {
        return reply("Pick two different accounts: the sender whose messages were scored, then the recipient.", where);
      }
      const actorUid = deps.hashUid(request.senderId);
      const targetUid = deps.hashUid(request.recipientId);
      // Scoped to the invoking guild. The same two accounts may be scored in
      // another server this bot serves; that history belongs to that server.
      const history = await deps.pairs.history(input.guildId, actorUid, targetUid);
      if (history === null || history.messages === 0) {
        return reply(
          "Guardian has no scored history for that pair in this server, so there is nothing to bundle. Guardian only keeps what it scored while enabled here, and the sender must be listed first.",
          where,
        );
      }
      if (!isBundleable(history)) {
        return reply(
          "That pair never rose above tier T0, so no message text was retained and there is nothing to bundle.",
          where,
        );
      }
      const bundle = await deps.pipeline.exportBundle(
        input.guildId,
        actorUid,
        targetUid,
        history.tier,
        history.rationale,
      );
      // The pipeline keeps its timeline under the same guild key, so a bundle
      // is only ever built from what was scored in this server. Null means the
      // memory of it is gone, most often after a restart.
      if (bundle === null) {
        return reply(
          "Guardian has no retained messages for that pair in this server, so there is nothing to bundle. Message memory is held in process and is empty after a restart.",
          where,
        );
      }
      const draft = buildReportDraft(bundle, history.rationale);
      return reply(
        [
          `Evidence bundle \`${bundle.bundleId}\` drafted at tier ${bundle.tier} with ${bundle.timeline.length} messages.`,
          "The report draft is attached. You are the reporter: read every line, then file it yourself at report.cybertip.org. Guardian has not sent it anywhere.",
          "This reply is visible only to you. Do not post the draft in a channel, and do not message either account about it.",
        ].join("\n"),
        where,
        [{ name: `guardian-report-draft-${bundle.bundleId}.txt`, content: draft }],
      );
    }

    case "verify": {
      const result = await deps.audit.verify();
      if (result.ok) {
        return reply(
          `Audit chain intact. ${result.checked} entries checked, head ${shortHash(result.head)}.`,
          where,
        );
      }
      return reply(
        `Audit chain broken at entry ${result.brokenAt} (${result.reason}): ${result.detail}. ${result.checked} entries checked before the break. Preserve the database as it is before anything else is written.`,
        where,
      );
    }
  }
}

/**
 * What any member sees. Rule 3 says this surface is overt, so the answer is
 * honest about whether Guardian is scoring. It stops there: the mod channel,
 * the excluded channels, the trusted roles, the band map, the timeout setting
 * and the tier counts are all operational detail, and the exclusion list in
 * particular tells a reader exactly where Guardian does not look.
 */
function formatPublicStatus(config: GuildConfig): string {
  return [
    isReady(config)
      ? "Guardian is on in this server. It reads messages in channels it has access to and scores conversation patterns, then tells the moderators when a pattern needs a human look."
      : "Guardian is installed in this server but is not scoring. A member with Manage Server finishes setup with /guardian setup.",
    "It stores age bands rather than birthdates, never images or video, and tiers describe message patterns for human review. They are not findings about any person.",
    "Settings and activity are shown to members with Manage Server. If a conversation here worries you, tell a moderator of this server.",
  ].join("\n");
}

function formatStatus(
  config: GuildConfig,
  counts: { T1: number; T2: number },
  head: { seq: number; hash: string },
): string {
  const roleLines = Object.entries(config.roleBands).map(
    ([roleId, band]) => `  <@&${roleId}>: ${BAND_LABELS[band]}`,
  );
  const lines = [
    `Scoring: ${isReady(config) ? "on" : "off"}${config.enabled && !config.modChannelId ? " (no mod channel yet)" : ""}`,
    `Mod channel: ${config.modChannelId ? `<#${config.modChannelId}>` : "not set"}`,
    `Default band for unmapped members: ${BAND_LABELS[config.defaultBand]}`,
    roleLines.length > 0 ? `Role bands:\n${roleLines.join("\n")}` : "Role bands: none mapped",
    `Trusted roles: ${config.trustedRoleIds.length > 0 ? config.trustedRoleIds.map((id) => `<@&${id}>`).join(", ") : "none"}`,
    `Excluded channels: ${config.excludedChannelIds.length > 0 ? config.excludedChannelIds.map((id) => `<#${id}>`).join(", ") : "none"}`,
    `Timeout on T2: ${config.autoTimeoutOnT2 ? `on, ${config.autoTimeoutMinutes} minutes` : "off"}`,
    `Last 7 days: ${counts.T1} pairs at T1 (watch), ${counts.T2} pairs at T2 (needs a human look)`,
    `Audit chain: ${head.seq} entries, head ${shortHash(head.hash)}`,
    "Tiers describe message patterns for human review. They are not findings about any person.",
  ];
  return lines.join("\n");
}

function shortHash(hash: string): string {
  return `${hash.slice(0, 12)}...`;
}

function reply(content: string, where: string, files?: ReplyFile[]): CommandReply {
  const checked = assertNoAccusation(content, where);
  for (const file of files ?? []) assertNoAccusation(file.content, `${where}.${file.name}`);
  return files ? { content: checked, ephemeral: true, files } : { content: checked, ephemeral: true };
}
